### ISSUE TITLE
tzname parsed as component but it be string (NoMethodError: to_ical)

### ISSUE THREAD

**Issue by taka-vagyok** [icalendar/icalendar#104]
I update redmine plugin and met have an error as follow
~~
NoMethodError (undefined method `to_ical' for "JST":String):
  icalendar (2.2.1) lib/icalendar/component.rb:40:in `block (2 levels) in ical_properties'
  icalendar (2.2.1) lib/icalendar/component.rb:39:in `map'
 ....
~~~

Reproduced code:
~~~
    cal = Icalendar::Calendar.new
    cal.timezone do |t|
      t.tzid = 'Asia/Tokyo'
      t.standard do |tst|
        tst.tzoffsetfrom = '+0900'
        tst.tzoffsetto   = '+0900'
        tst.tzname       = 'JST'
        tst.dtstart      = '19700101T000000'
      end
    end
~~~

I believe that this is initializing or parsing bug.

**Comment by rahearn** [comment]
I don't see an error when running the provided code. Can you supply some more information?

**Comment by mlr** [comment]
Hi, I'm seeing this same issue.  I'm using the code straight from the README:

```
timezone do |t|
  t.tzid = "America/Chicago"

  t.daylight do |d|
    d.tzoffsetfrom = "-0600"
    d.tzoffsetto   = "-0500"
    d.tzname       = "CDT"
    d.dtstart      = "19700308T020000"
    d.rrule        = "FREQ=YEARLY;BYMONTH=3;BYDAY=2SU"
  end

  t.standard do |s|
    s.tzoffsetfrom = "-0500"
    s.tzoffsetto   = "-0600"
    s.tzname       = "CST"
    s.dtstart      = "19701101T020000"
    s.rrule        = "FREQ=YEARLY;BYMONTH=11;BYDAY=1SU"
  end
end
```

```
NoMethodError (undefined method `to_ical' for "CDT":String):
```

I'm using icalendar version 2.3.0, tzinfo 0.3.42, and ruby 2.1.3.  Any insights?

**Comment by rahearn** [comment]
I'm still unable to reproduce the error with the supplied code, ruby 2.1.3, icalendar 2.3.0 and tzinfo 0.3.42 installed (though it isn't used by the provided example).

Can either of you supply a full ruby file that demonstrates the error on your machines? Please include the versions of any used libraries or rubies. I should be able to run the example via just `ruby your_file.rb`

**Comment by mlr** [comment]
@rahearn Thanks very much for your reply.  I was unable to reproduce with the following:

```ruby
#!/usr/bin/env ruby

require 'icalendar'
# require ::File.expand_path('../config/environment',  __FILE__)

calendar = Icalendar::Calendar.new

calendar.timezone do |t|
  t.tzid = "America/Chicago"

  t.daylight do |d|
    d.tzoffsetfrom = "-0600"
    d.tzoffsetto   = "-0500"
    d.tzname       = "CDT"
    d.dtstart      = "19700308T020000"
    d.rrule        = "FREQ=YEARLY;BYMONTH=3;BYDAY=2SU"
  end

  t.standard do |s|
    s.tzoffsetfrom = "-0500"
    s.tzoffsetto   = "-0600"
    s.tzname       = "CST"
    s.dtstart      = "19701101T020000"
    s.rrule        = "FREQ=YEARLY;BYMONTH=11;BYDAY=1SU"
  end
end

puts calendar.to_ical
```

The above works just fine.  However, when I add my Rails app's environment, I then see the reported error.  I think yo

```ruby
# Added after require 'icalendar'
require ::File.expand_path('../config/environment',  __FILE__)
```

**Comment by mlr** [comment]
Sorry to hijack this issue, but I've narrowed down the problem to a specific set of gems.  Here is a project that reproduces the error: https://github.com/mlr/rails3-icalendar-error

It's a completely fresh Rails 3.2 application that includes the icalendar and the carrierwave-mongo gems. I haven't been able to narrow down what exactly within the carrierwave-mongo gem causes the issue,  however the same problem does not occur with a fresh Rails 4.2 project.

You can run `bundle exec ruby icalendar-error.rb` from the project's root to reproduce the error.

**Comment by rahearn** [comment]
@mlr thanks. Could it potentially be a mongoid v3.1.7 (in the rails 3 project) vs mongoid v4.0.2 (in the rails 4 project) issue?

I'll try to investigate more deeply when I next have some time.

**Comment by taka-vagyok** [comment]
I'm sorry to late response. I reproduced on redmin2.x. So it may relate to rails or anything.
https://github.com/taka-vagyok/redmine_ical
When I can reproduced  simpler, I report again.
