### ISSUE TITLE
support apple's proprietary structured location field

### ISSUE THREAD

**Issue by bitcoder** [icalendar/icalendar#108]
add support of apple's proprietary field "X-APPLE-STRUCTURED-LOCATION", which is used in Apple devices, instead of "geo" field.

Example bellow:
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=Aveiro;X-APPLE-RADIUS=14
 938.10232458485;X-TITLE=hometown:geo:40.641185,-8.653617

I was unable to find an oficial specification for this field though..

**Comment by mattvague** [comment]
Not super pretty and could probably be done a lot better, but the following will accomplish this for you using a custom value type:

```
module Icalendar
  class AppleStructuredLocation < Icalendar::Value

    def initialize(title, address, coordinate, radius: 72)
      @title            = title
      @address     = address
      @coordinate = coordinate.to_s
      @radius        = radius

      super "VALUE=URI;X-ADDRESS=#{@address};X-APPLE-RADIUS=#{@radius}
             ;X-TITLE=#{@title}:geo:#{@coordinate}"
    end

    def value_ical
      value
    end

    def to_ical(default_type)
      "#{params_ical};#{value_ical}"
    end
  end
end
```

You can use it like so: `Icalendar:: AppleStructuredLocation.new("Some place", "123 Fake Street", "123.45,-999.99")

**Comment by bitcoder** [comment]
ok thanks @mattvague !

**Comment by rahearn** [comment]
You could also do the same with the standard value types like so:

```
event = Icalendar::Event.new
event.x_apple_structured_location = Icalendar::Values::Uri.new("geo:40.641185,-8.653", {
  'x-address' => 'Aveiro',
  'x-apple-radius' => '14938.102',
  'x-title' => 'hometown'
})
```

**Comment by mattvague** [comment]
@rahearn Ah, I knew there must be a better way. Thanks!

**Comment by boncey** [comment]
In case anyone is looking for an example of parsing the geo coordinates from a calendar...

```
    locations = cal_event.x_apple_structured_location

    if (!locations.empty? && locations.first.scheme == "geo")
      location = locations.first.value
      geo = location.opaque
      coords = geo.split(",")

      latitude = coords[0].strip
      longitude = coords[1].strip
    end
```

**Comment by rahearn** [comment]
It seems like the event map is pretty picky about form, and the events need both the structured data and standard `location` to be present and match. I got these two events to both display the map in Apple Calendar on macOS 14.0:

```
require 'icalendar'

c = Icalendar::Calendar.new

c.event do |e|
  e.dtstart = 1.hour.from_now
  e.dtend = 2.hours.from_now
  e.summary = "Portugal town"
  e.location = "Aveiro\nPortugal"
  e.x_apple_structured_location = Icalendar::Values::Uri.new("geo:40.641185,-8.653", {
    "x-title" => "Aveiro\\nPortugal"
  })
end

c.event do |e|
  e.dtstart = 3.hours.from_now
  e.dtend = 4.hours.from_now
  e.summary = "Baltimore restaurant"
  e.location = "Cypriana\n105 W 39th St Baltimore MD 21210 United States"
  e.x_apple_structured_location = Icalendar::Values::Uri.new("geo:39.336032,-76.622119", {
    "x-title" => "Cypriana",
    "x-address" => "105 W 39th St Baltimore MD 21210 United States"
  })
end

File.open("/Users/myuser/Desktop/maps.ics", "w") do |f|
  f.write(c.to_ical)
end
```

It seems like the key is that `e.location` matches what is in the combination of `x-title` and `x-address` paramaters of the `x-apple-structured-location`. Without `e.location`, or with mismatches in the title and/or address, it looks like the app doesn't show the calendar.
