### ISSUE TITLE
Upgrading from 1.5.2 to 2.2.2: undefined method `recurrence_rules' 

### ISSUE THREAD

**Issue by greggawatt** [icalendar/icalendar#111]
I'm getting 
````
NoMethodError (undefined method `recurrence_rules' for #<Icalendar::Event:0x007f9c321c6da0>):
````

Trying to upgrade to the newest version. 

Here is the block of code:

````
cals = Icalendar.parse(resp.body.untaint)
      cal = cals.first
      evts = cal.events
      evts.each do |evt|
        if evt.recurrence_rules.empty?
````

Did this get renamed or removed?

**Comment by greggawatt** [comment]
It seems like it is now ````rrule````

**Comment by rahearn** [comment]
Sorry it's taken so long to get back to you - yes, it is now `rrule`. Where possible method names now match the property names they represent.

**Comment by greggawatt** [comment]
Is there a changelog of the different method names for this version?

**Comment by rahearn** [comment]
No, unfortunately not yet.

**Comment by greggawatt** [comment]
:-1:
