### ISSUE TITLE
Splitting RRules into seperate Events

### ISSUE THREAD

**Issue by calumgunn** [icalendar/icalendar#113]
I'd like to be able to ask an Event to give me every time it occurs, according to its recurrence rule.

I've written a lightweight parser for this in a small project I'm working on, but it doesn't extend to every use case - is this something you (or anyone!) would be interested in my fleshing out and submitting to the gem? It's certainly been useful functionality for me!

**Comment by rahearn** [comment]
Hi @calumgunn check out the https://github.com/icalendar/icalendar-recurrence project. I think it does what you're looking for.
