### ISSUE TITLE
EXDATE and RDATE wrongly take Date as DateTime

### ISSUE THREAD

**Issue by yoshinari-nomura** [icalendar/icalendar#117]
Hi, I'm seeking a good replacement of RiCal.

In some cases, EXDATE and RDATE seem to mistakenly convert Date into floating DateTime.
Here is the details:

``` Ruby
ev = ::Icalendar::Event.new
ev.append_exdate [
  ::Icalendar::Values::Date.new("20150520"),
  ::Icalendar::Values::Date.new("20150521")
]
puts ev.to_ical
```
got:
```
BEGIN:VEVENT
DTSTAMP:20150516T103950Z
UID:0766cb45-6c3b-4354-ac70-eaf1a69cdf9f
EXDATE:20150520T000000,20150521T000000
END:VEVENT
```
while expected:
```
BEGIN:VEVENT
DTSTAMP:20150516T103950Z
UID:0766cb45-6c3b-4354-ac70-eaf1a69cdf9f
EXDATE:20150520,20150521
END:VEVENT
```

**Comment by espen** [comment]
You are using an array. To specify multiple entries you must call append_exdate multiple times.

This works:

```
append_exdate Icalendar::Values::Date.new("20150520")
```

**Comment by yoshinari-nomura** [comment]
Thanks @espen

Yes, but it requires an additional `each`...
In addition, that creates multiple lines of EXDATE like:
```
BEGIN:VEVENT
DTSTAMP:20150518T141220Z
UID:f87337ce-364d-4506-81f7-a9b26fd54269
EXDATE;VALUE=DATE:20150520
EXDATE;VALUE=DATE:20150521
END:VEVENT
```
I prefer the single-line form if possible.

Since I have some code using RiCal, which accepts an array as expected,
I wanna switch to icalendar with minimum modifications.

Besides my personal moans, 
If `append_exdate` does not take array, I think it should emit some exception for safety.

**Comment by rahearn** [comment]
Ideally the array version should work. I consider it a bug that it doesn't.

**Comment by espen** [comment]
There seem to be two problems:

1) Array converts Date to DateTime
2) Array results in multiple EXDATE instead of adding to one entry.

```
ev = Icalendar::Event.new
ev.exdate = [ Icalendar::Values::Date.new("20150520"), Icalendar::Values::Date.new("20150521") ]
ev.exdate.first.class
=> Icalendar::Values::DateTime
ev.to_ical
=> "BEGIN:VEVENT\r\nDTSTAMP:20150518T161212Z\r\nUID:e5de8843-e51d-49f9-9ba0-5d4b0088dde8\r\nEXDATE:20150520T000000\r\nEXDATE:20150521T000000\r\nEND:VEVENT\r\n"
```

**Comment by yoshinari-nomura** [comment]
thanks @rahearn 

As I skimmed the code, [this code](https://github.com/icalendar/icalendar/blob/master/lib/icalendar/has_properties.rb#L167) seems to re-bless the objects as klass (`DateTime`).

This might be somewhat a deep problem because EXDATE/RDATE are cofigured to take only `DateTime`
[here](https://github.com/icalendar/icalendar/blob/master/lib/icalendar/event.rb#L35)

Therefore, this code also does not work:
```Ruby
ev = ::Icalendar::Event.new
ev.exdate = "20150520"
puts ev.to_ical
```
I think we need some smart factory to create DateTime or Date.

**Comment by rahearn** [comment]
Couple of notes here.

1) If you want either a date or date time, you can now use: `event.dtstart = Icalendar::Values::DateOrDateTime.new(value, params).call`

2) 
```
ev = ::Icalendar::Event.new
ev.append_exdate [
  ::Icalendar::Values::Date.new("20150520"),
  ::Icalendar::Values::Date.new("20150521")
]
```

now behaves as you would expect, outputting Date values.

3) `ev.exdate = [date 1, date 2]` will still output on two lines. `ev.exdate = [[date 1, date 2]]` will output a single line.

**Comment by yoshinari-nomura** [comment]
Thanks!
