### ISSUE TITLE
Expose CN for attendee

### ISSUE THREAD

**Issue by rahulsom** [icalendar/icalendar#118]
Right now Attendee is parsed as a URI and only the `mailto:foo@bar.com` part is being exposed.
I'm looking to access the CN part of the Attendee.

E.g.

```
ATTENDEE;CN=Foo Bar;CUTYPE=INDIVIDUAL:mailto:foo@bar.com
```

**Comment by rahearn** [comment]
Try accessing the value's `ical_params` method.

**Comment by rahulsom** [comment]
:+1:
