### ISSUE TITLE
Random UTF

### ISSUE THREAD

**Issue by Event-Software** [icalendar/icalendar#121]
I'm new at this so not sure if I'm doing something wrong, but when using icalendar gem, sometimes a description or summary will randomly contain UTF code.   Not all entries in an ical feed, just some of them sometimes and they look no different than any others.

SUMMARY:Tech Job Fair – Scottsdale(AZ) – Jul 1, 2015

ends up being 

["Tech Job Fair \xE2\x80\x93 Scottsdale(AZ) \xE2\x80\x93 Jul 1", " 2015"]

once it is stored in the database, but again only for some events, not all in a feed.

SUMMARY:Phoenix Investor Roundtable Sponsored by Grow Southwest

this one turns out as 

Phoenix Investor Roundtable Sponsored by Grow Southwest

as I expect.  

Does it change once it encounters some certain character? How can I proactively look for this.

**Comment by Event-Software** [comment]
uri = URI.parse(url)
calendar = Net::HTTP.get(uri)
new_calendar = Icalendar.parse(calendar)

This is how I get the file, maybe this matters.

**Comment by espen** [comment]
I haven't noticed any unicode issues. Can you provide a failing test for it? Perhaps there is anoter encoding in your code or database?

**Comment by Event-Software** [comment]
Out of the three feeds I'm playing with, only 1 has this issue.  The other 2 work fine.  So I'd say the database is working.  In the rails database config it is shown with encoding 'unicode', and has been from its creation.

You can test with this.

calendar = Net::HTTP.get_response(URI.parse('http://aztechbeat.com/events/?ical=1' ))
new_cal = Icalendar.parse(calendar.body)

You can then see all the text fields contain the unicode escapes.

**Comment by rahearn** [comment]
Looks like a data issue, maybe?

Taking your example, I see the unicode escapes by just running:

`Net::HTTP.get_response(URI.parse('http://aztechbeat.com/events/?ical=1')).body`

**Comment by Event-Software** [comment]
I see some of the escapes, but there are fields with no escapes in the file, yet when iCalendar parses them it adds them in.
The second event with "SUMMARY:Tech Job Fair" Contains no escapes in that line yet when parse is fully escaped.

Would that still be a file issue?  Sorry I'm new with this type of parsing.

**Comment by rahearn** [comment]
I'm only seeing one "Tech Job Fair" entry in that source, which has the escapes.

This feed fails a validation service, which might also be a part of the problem: http://severinghaus.org/projects/icv/?url=http%3A%2F%2Faztechbeat.com%2Fevents%2F%3Fical%3D1

**Comment by Event-Software** [comment]
Its beyond spooky that I was just using that validator 30 seconds before you posted here to check the same thing.

I see all the escapes now in rails console, notepad++ must have been hiding them.

So maybe this is just a case of a bad formed file.  Is there a way to strip them out if I find files with this problem?

**Comment by Event-Software** [comment]
Okay so I'm not sure if its the file thats bad or what. but this is what is happening.  It looks like some line are interpreted as an Array not a Text.  When I slam the array into my model that has a string field.  it puts it in ["first line", "second line"] format.  

So they file may be escaping everything but forgetting comma's thus making it look like an array.  However iCalendar is allowing an array in its fields.  

Should icalendar allow summary/location/description fields to contain arrays?

**Comment by Congrammers** [comment]
I still had problem with this, it split the content of `DESCRIPTION` based on semicolon (';') and comma (','), wouldn't be possible to join them if both characters contained in single description.
