### ISSUE TITLE
[Question] Create a series of events

### ISSUE THREAD

**Issue by PericlesTheo** [icalendar/icalendar#124]
Hey everyone,

With calendar apps you can create a series of events rather than single events so that when you try to delete an event, you get the *Do you want to delete any future events* popup.

Is it possible to achieve the same with the gem?

**Comment by rahearn** [comment]
Yes, you'll want to learn more about the `rrule` `rdate` and `exdate` properties from the [icalendar spec](https://tools.ietf.org/html/rfc5545)

**Comment by espen** [comment]
Also have a look at https://github.com/icalendar/icalendar-recurrence

**Comment by PericlesTheo** [comment]
@espen @rahearn cool I don't know how I missed that. Cheers :+1:
