### ISSUE TITLE
What does the publish method on a Calendar object do?

### ISSUE THREAD

**Issue by pitosalas** [icalendar/icalendar#125]
What does the publish method on a Calendar object do?

Thanks!

p.s. Are there any sample apps that use this gem that I could use to learn more about its usage?

**Comment by espen** [comment]
See https://github.com/icalendar/icalendar/blob/master/lib/icalendar/calendar.rb#L23 and https://tools.ietf.org/html/rfc2446#page-15

**Comment by pitosalas** [comment]
Thanks. I had looked at the standard but didn’t find a definition for ip_method. 

- Pito

**Comment by espen** [comment]
'ip_method' is used because 'method' is a reserved word. So 'method' is what is defined in the iCalendar spec.

Please close this issue.
