### ISSUE TITLE
Subclassing Icalendar::Event?

### ISSUE THREAD

**Issue by markquezada** [icalendar/icalendar#126]
Hi,

I have a specific type of event in my domain model and I wanted to subclass `Icalendar::Event` so I could independently test each value being set for the calendar event. Something like this:

```
  class SpecialIcalendarEvent < Icalendar::Event

    def initialize(event)
      super()
      @event = event
    end

    def dtstart
      Icalendar::Values::DateTime.new(@event.starts_at, tzid: tzid)
    end

    def dtend
      Icalendar::Values::DateTime.new(@event.ends_at, tzid: tzid) if @event.ends_at.present?
    end

    def duration
      Icalendar::Values::Duration.new('1H') unless @event.ends_at.present?
    end

  private

    def tzid
      @event.timezone
    end
  end
end
```

But this doesn't work. I took a look and `Icalendar::Event` and I see `optional_single_property` calls, etc. I'm guessing the above doesn't work because values have to be explicitly set, not just available as a property/method. I tried explicitly setting the properties via the methods in the initializer like so:

```
    def initialize(event)
      super()
      @event = event
      self.dtstart = dtstart
    end
```

... but that doesn't work either. I'm generating it like this:

```
  calendar = Icalendar::Calendar.new
  calendar.add_event(SpecialIcalendarEvent.new(@event))
  calendar.add_timezone(@event.ical_timezone) if @event.ical_timezone
  calendar.publish
  calendar.to_ical
```

I get this output:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:icalendar-ruby
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Pacific/Honolulu
BEGIN:STANDARD
DTSTART:19470608T023000
TZOFFSETFROM:-1130
TZOFFSETTO:-1000
TZNAME:HST
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT

END:VEVENT
END:VCALENDAR
```

Not sure if I'm doing something wrong or if my approach is flawed. I was trying to avoid a singular method call that generates and returns the icalendar event but that seems like the only way to go. Thoughts?

**Comment by rahearn** [comment]
The problem is here: https://github.com/icalendar/icalendar/blob/master/lib/icalendar/component.rb#L35

Since you're subclassing `self.class.properties` ends up being an empty array.

A quick fix would involve adding this to `SpecialIcalendarEvent`

```
def self.properties
  ancestors[1].properties
end
```
