### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by pitosalas** [icalendar/icalendar#128]
I tried reading the code and trying experiments but I am a bit stuck.

I am working just with one timezone, USA Eastern Timezone. I have times and dates in only that timezone. I have a number of simple events. I have gotten it to work, except for the TZ. I know it's working because I can subscribe to the feed with with OS X Calendar.app. But when I load the same feed into a Google calendar, it reads all the dates and times as GMT. 

I need to indicate the timezone for the start and end time for each event. Here's my code:

class ICalAdaptor
  def initialize
    @cal = Icalendar::Calendar.new
    tzid = "America/New_York"
    tz = TZInfo::Timezone.get tzid
    binding.pry
    @cal.add_timezone tz
  end

  def feed_begin
  end

  def feed_end
  end

  def feed_event(title, dt_start, dt_end, desc, url)
    event = Icalendar::Event.new
    event.dtstart = dt_start
    event.dtend = dt_end
    event.summary = title
    event.description = desc
    event.url = url
    @cal.add_event(event)
  end

  def feed_render
    @cal.to_ical
  end
end

This code errors with "NoMethodError: undefined method `parent=' for #<TZInfo::DataTimezone: America/New_York>" at this line: `@cal.add_timezone tz`

I am stumped. Anyone know about the TZ support in calendar? Thanks!

**Comment by rahearn** [comment]
You need to add an `Icalendar::Timezone` to the calendar, instead of a `TZInfo::Timezone`. You can get the former from the latter by first `require "icalendar/tzinfo"` and then:

```
tz = TZInfo::Timezone.get tzid
@cal.add_timezone tz.ical_timezone(Date.today)
```

`Date.today` should be substituted with an example date from your events if you are building a calendar with historic data. For most cases of events in the near term future `Date.today` is fine.

**Comment by pitosalas** [comment]
Confused: You say use ICalendar::Timezone but your example says
TZInfo::Timezone. Typo?

-- Pito

**Comment by rahearn** [comment]
I did have a typo, but that wasn't it. Calling `ical_timezone` on a TZInfo::Timezone returns an `ICalendar::Timezone` that we can pass to `add_timezone`

The problem with the code is that you can't pass a `Date` to it. You have to pass either a `Time` or a `DateTime`. So, it should have read:

```
tz = TZInfo::Timezone.get tzid
@cal.add_timezone tz.ical_timezone(Time.now)
```

**Comment by pitosalas** [comment]
Thanks... By the way, what is the purpose of the time stamp that goes into
the "header"? You say it should be something from the events to follow, but
Time.now would be ok too. What is it doing semantically?

-- Pito

**Comment by rahearn** [comment]
the time is used to find the appropriate timezone period to look up the transition rules for daylight savings time. These change, so if you have historical data you may need different rules than what is current.
