### ISSUE TITLE
Calendar feed works on mac OS X Calendar.app but not on Google Calendar

### ISSUE THREAD

**Issue by pitosalas** [icalendar/icalendar#129]
http://cosi105b-f2015.s3-website-us-west-2.amazonaws.com/content/lectures/schedule.ical

This feed, generated with this gem, works great in OS X calendar.app. The times and dates I am supplying are meant to be in  the America/New_York timezone. I believe the datetime values in the feed are GMT and calendar.app is doing the right thing with respect to the time zone.

However when I use this same feed into Google calendar, the times for the events are all 4 hours early implying that google is not respecting the timezone.

My diagnosis may not be correct, but I can't find the info I need regarding possible problems with googles ical parsing. Does anyone have any experience with that? Thanks!

**Comment by rahearn** [comment]
It looks like the events are all specified as being in "floating" local time zone, not America/New_York. That's probably responsible for the difference between Calendar.app and Google. You have to specify a tzid ical_param to set the event to be either in a specific timezone or in UTC.

**Comment by pitosalas** [comment]
Sounds right. I've plowed through the source and google and can't identify the right incantation. Could you help me with a pointer? Thanks,

Pito

here's my code so far, which almost works. I've identified as a comment where the change should go as far as I can figure out so far, Thanks!

require 'icalendar'
require 'icalendar/tzinfo'

class ICalAdaptor
  def initialize
    @cal = Icalendar::Calendar.new
    tzid = "America/New_York"
    tz = TZInfo::Timezone.get tzid
    @cal.add_timezone tz.ical_timezone(Time.now)
  end

  def feed_begin
  end

  def feed_end
  end

  def feed_event(title, dt_start, dt_end, desc, url)
    event = Icalendar::Event.new
    event.dtstart = dt_start
    event.dtend = dt_end
    event.summary = title
    event.description = desc

### This is where I need to add another line. I am not sure if its on the whole event, or a separate
### line for dtstart and dtend

    @cal.add_event(event)
  end

  def feed_render
    @cal.to_ical
  end
end

**Comment by rahearn** [comment]
From your example:

```
event.dtstart = dt_start
event.dtend = dt_end
```

It is there that you need to specify the tzid. Do that with something like:

```
event.dtstart = Icalendar::Values::DateOrDateTime.new(dt_start, tzid: 'UTC').call
event.dtend = Icalendar::Values::DateOrDateTime.new(dt_end, tzid: 'UTC').call
```

if your times are coming in in UTC. Substitute the appropriate timezone id if not.

**Comment by pitosalas** [comment]
That code only works on 1.x. Should I not be using iCalendar 2.x?

**Comment by rahearn** [comment]
2.x is definitely what you should be using. The code I wrote should definitely not work on 1.x, what errors are you getting on 2.x?

**Comment by pitosalas** [comment]
Thanks for your help so far:

Ok, this is really weird… My error is:
NameError: uninitialized constant Icalendar::Values::DateOrDateTime

When I inspect my copy of the gem I get:

cosi165a-f2015(master)> gem pristine icalendar
Restoring gems to pristine condition...
HEADS UP! iCalendar 2.0 is not backwards-compatible with 1.x. Please see the README for the new syntax

HEADS UP! icalendar 2.2.0 switches to non-strict parsing as default. Please see the README if you
rely on strict parsing for information on how to enable it.

ActiveSupport is required for TimeWithZone support, but not required for general use.
Restored icalendar-2.3.0
cosi165a-f2015(master)> gem which icalendar
/Users/pitosalas/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/icalendar-2.3.0/lib/icalendar.rb
cosi165a-f2015(master)> cd /Users/pitosalas/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/icalendar-2.3.0/
icalendar-2.3.0> find . -name date_or_date_time.rb
icalendar-2.3.0> find . -name date.rb
./lib/icalendar/values/date.rb
icalendar-2.3.0> find . -name date_or_date_time.rb

Meaning that date_or_date_time.rb is not present locally. And yet I see it in the github directory. Is my gem coming from the wrong place, or am I missing something else?

Pito Salas
Brandeis Computer Science
Feldberg 131

**Comment by rahearn** [comment]
My mistake. Looks like I haven't released a gem since adding the `DateOrDateTime` class. You can either use the gem directly from github, or use `Icalendar::Values::Date` or `Icalendar::Values::DateTime` depending on if you need just dates (for all-day events) or dates & times.

**Comment by mftaff** [comment]
Nice simple fix :-) 
Thanks
