### ISSUE TITLE
Is support for X-ALT-DESC possible?

### ISSUE THREAD

**Issue by andreimoment** [icalendar/icalendar#130]
MS Outlook uses this property to include an HTML-based description. Is there a way to add this property to icalendar, along with the description?

See: http://icalevents.com/4019-ics-feed-generation-with-html/ and http://stackoverflow.com/questions/854036/html-in-ical-attachment

Example:

```
X-ALT-DESC;FMTTYPE=text/html:<p>This is an example description.</p>
```

**Comment by espen** [comment]
You can add custom X-events like this: `event.x_alt_desc = "content"`.

**Comment by aflatten** [comment]
To be a little more specific, here's how to also include the format type:
```
event.x_alt_desc = Icalendar::Values::Text.new('<p>This is an example description.</p>', { 'FMTTYPE' => 'text/html' })
```

**Comment by andreimoment** [comment]
Thank you so much! I built an ics builder for a cms specialized in events
and this will allow for outlook specific formatting.
