### ISSUE TITLE
[Feature Request] Icalendar::Event.parse

### ISSUE THREAD

**Issue by schnika** [icalendar/icalendar#131]
# Feature Request

The library already supports parsing ics files containing multiple calendars. In my opinion it would be a great addition to the library if one would be able to parse single ical events and return an `Icalendar::Event` object with the respective values (like it is already done via `Icalendar.parse`).

## Usecase

Calendar aggregator. Where multiple calendar sources are getting imported and broken down to its events. Each event is stored individually in a document db. 
In case you want to provide an aggregated calendar there is __as far as I can see__ no way to parse a simple `VEVENT` in order to build an `Icalendar::Event` instance.

## Example

    ical_source = 
        BEGIN:VEVENT
        DTSTAMP:20151012T143720Z
        UID:o1qhr5pbukriorel7rnkll5f6o@google.com
        DTSTART:20140624T191500Z
        DTEND:20140624T194500Z
        CREATED:20140624T184350Z
        DESCRIPTION:Awesome event
        LAST-MODIFIED:20140624T184350Z
        SUMMARY:New matches 14/15
        X-INTERNAL-ID:o1qhr5pbukriorel7rnkll5f6o
        TRANSP:TRANSPARENT
        END:VEVENT

    ical_event = Icalendar::Event.parse(ical_source)
    
    ical_event.uid
    => "o1qhr5pbukriorel7rnkll5f6o@google.com"
    ical_event.dtstamp 
    => 20151012T143720Z
    ical_event.dtstart 
    => 20140624T191500Z
    ical_event.dtend 
    => 20140624T194500Z
    ...
    ical_event.x_internal_id 
    => o1qhr5pbukriorel7rnkll5f6o

Then one can simply add this event via `ical.add_event(ical_event)` to an icalendar instance.

If you have further questions on this I would be happy to answer any questions. I would be also happy to build this feature as well and contribute to this library if you are with me on this FR.

**Comment by AlejandroPiquer** [comment]
Hello. I have a problem with icalendar. I'm trying to import multiple events at the same time, reading a .txt and writting trhough python to a .ics file. Do you know how to import many events in the same time? Could you tell me how to do it?

**Comment by schnika** [comment]
@AlejandroPiquer this is a pull request and you question has nothing to do with it. Since you are working with python, this is not the place to look for answers :). There is a python project: Please find your answers and documentation there: 
http://icalendar.readthedocs.org/en/latest/usage.html
https://github.com/collective/icalendar

**Comment by rahearn** [comment]
@schnika sorry it's taken me so long to respond to this. I'd definitely be interested in this feature and would love help on implementing it

**Comment by schnika** [comment]
@rahearn thanks for your reply. I added a first draft as a PR with a couple of questions regarding the design of the interface. Tell me what you think.
https://github.com/icalendar/icalendar/pull/143

**Comment by schnika** [comment]
Implemented with #143
