### ISSUE TITLE
[Feature Request] URL of your event's landing page

### ISSUE THREAD

**Issue by weixing2014** [icalendar/icalendar#133]
Hey, 

I'm a big fan of this gem. However, I'm not sure if I can put a landing page url in an event. Since Google Calendar, Mac iCalendar and MS Outlook all can display the url in some way, maybe you want to put this feature in the gem and then we can set the landing page url when creating an event.

Thanks!

**Comment by espen** [comment]
You probably want: event.url = 'http://google.com'

**Comment by weixing2014** [comment]
@espen Oh, I can't believe I missed this. Thanks! This issue can be closed.
BTW, In order to prevent anyone from asking the same question in the future, maybe you want to put this in the examples :)
:+1:

**Comment by JonMidhir** [comment]
@welxing2014 Maybe _you_ want to put this in the examples :stuck_out_tongue_winking_eye: 

Added in https://github.com/icalendar/icalendar/pull/134.

**Comment by weixing2014** [comment]
@JonMidhir Thanks for adding this in the example! I almost forgot this is a public repository, so, yeah, next time :+1:

**Comment by espen** [comment]
Unfortunately I haven't found a good intro to the iCalendar-spec yet. The best I found so far is a cut down description of the spec at http://www.kanzaki.com/docs/ical/. Perhaps the readme should include a link to it and with some info about what properties that can be applied to the icalendar gem is what is found in the icalendar spec. Or are there any good sites to link to for devs who don't want to read the entire RFC2445?
