### ISSUE TITLE
ICS Files coming through as "Floating Time Zone"

### ISSUE THREAD

**Issue by laneystroup** [icalendar/icalendar#135]
Hi there,

For some reason, all of ics that I create are coming through as "Floating Time Zone" on my Mac. This works well for events that I want to occur at the same time every day (e.g. if I want to run at 6:30AM, regardless of where I am in the world), but not for fixed time events.

Is there a way in icalendar to distinguish between these two types of events (floating vs. fixed?). Here is my code at present:

def ics_file
    require 'icalendar/tzinfo'

    event = Icalendar::Event.new

    event.dtstart     = self.start_time.in_time_zone(Time.zone)
    event.dtend       = self.end_time.in_time_zone(Time.zone)
 
    event.summary     = self.name
    event.description = self.search_content

    event.alarm do |a|
      a.action  = "DISPLAY"
      a.summary = "Alarm notification"
      a.trigger = "-P7DT0H0M0S" # 7 days before
    end

    event.alarm do |a|
      a.action  = "DISPLAY"
      a.summary = "Alarm notification"
      a.trigger = "-P1DT0H0M0S" # 1 day before
    end

    event.alarm do |a|
      a.action        = "AUDIO"
      a.trigger       = "-PT15M"
      a.append_attach "Basso"
    end

    cal = Icalendar::Calendar.new

    tzid = Time.zone.name
    tz = TZInfo::Timezone.get tzid
    timezone = tz.ical_timezone start_time.in_time_zone(Time.zone)

    cal.add_timezone timezone
    cal.add_event(event)
    cal.publish
    cal.to_ical

  end

Thanks,
Laney

**Comment by rahearn** [comment]
You need to specify the tzid explicitly on the dtstart and dtend lines.

`event.dtstart = Icalendar::Values::DateTime.new self.start_time.in_time_zone(Time.zone), tzid: Time.zone.name`
