### ISSUE TITLE
wrong constant name X-event-series

### ISSUE THREAD

**Issue by grimsell** [icalendar/icalendar#136]
When I try to parse an ical file from Confluence Team Calendar I get the following error message:
```
W, [2015-12-01T08:29:37.021691 #13607]  WARN -- : No method "sequence=" for component #<Icalendar::Timezone:0x00000003a98ac8>. Appending to custom.
================================================================================
scheduler caught exception:
wrong constant name X-event-series
/var/lib/gems/1.9.1/gems/icalendar-2.3.0/lib/icalendar/parser.rb:97:in `const_defined?'
/var/lib/gems/1.9.1/gems/icalendar-2.3.0/lib/icalendar/parser.rb:97:in `parse_component'
/var/lib/gems/1.9.1/gems/icalendar-2.3.0/lib/icalendar/parser.rb:27:in `parse'
/var/lib/gems/1.9.1/gems/icalendar-2.3.0/lib/icalendar.rb:16:in `parse'
/media/sf_apps/eclipse/idainfront-Ida Dashing Dashboard/ws/dashboard/jobs/confluence_calendar.rb:15:in `update_calendar'
/media/sf_apps/eclipse/idainfront-Ida Dashing Dashboard/ws/dashboard/jobs/confluence_calendar.rb:22:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
/var/lib/gems/1.9.1/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
/var/lib/gems/1.9.1/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
================================================================================
```

This is my code:

```
require 'net/http'
require 'icalendar'


def get_calendar
  uri = "https://myconfluence/rest/calendar-services/1.0/calendar/export/subcalendar/private/b07e715704a9eefaaf0d66f3918d334aff61fd72.ics"
  response = get_http(uri, "john", "doe")
  response.body
end

def update_calendar
  ics       = get_calendar
  calendars = Icalendar.parse(ics)
end
```

Is this a bug or am I doing something wrong here?

**Comment by espen** [comment]
Can you put the ics in a gist?

**Comment by grimsell** [comment]
I’ll send you the file directly since it might contain some sensitive data.

**Comment by espen** [comment]
I'd suggest that you remove the sensitive data and put it in a gist so everyone can review it.

I did however have a quick look at it and see there are multiple entries with ```BEGIN:X-EVENT-SERIES```. I'm not so familiar with this but it looks to be a valid part of the spec. However I assume the iCalendar parser only supports the standard components being eventc / todoc / journalc / freebusyc /
                / timezonec. So I guess the solution is for the parser to ignore x-components.

**Comment by grimsell** [comment]
Here is a ics that reproduce the problem: https://gist.githubusercontent.com/grimsell/6dd264910832e9af95d1/raw/262698d0751b3a8725e576771af0467640f8d470/gistfile1.txt

**Comment by espen** [comment]
This is due to the parser checking a constant with dashes (from https://github.com/icalendar/icalendar/blob/master/lib/icalendar/parser.rb#L101). So it fails when trying "X-event-series".

Try changing ```downcase``` to ```underscore``` on line 101 and 108. This works with your file. However I haven't ran the test suite or know if this will case any issues. I'm suspecting this should be replaced a few other places in that file too.

**Comment by rahearn** [comment]
Closing this to focus on the more general solution in #142
