### ISSUE TITLE
Subscribe to calendar

### ISSUE THREAD

**Issue by l33z3r** [icalendar/icalendar#137]
I generate a calendar that parses correctly when imported ot iCal. 

However, when I try to subscribe to the same calendar via that url, I get an error in iCal. 

The error just simply says error -1 when I try to subscribe. 

Do I need to add some more metadata to the generated calendar to allow subscription to it?

**Comment by schnika** [comment]
@l33z3r. Please show me the contents of you ical file via a pastebin.

**Comment by l33z3r** [comment]
Hi @schnika, thanks for replying. 

I figured out the problem.

The file was in the correct format, but it has to be hosted on a public URL before it can be imported.

I had it hosted on a URL that was only accessible from inside our office.

thanks anyway.
