### ISSUE TITLE
How to access to do list in Icalendar::Todo class

### ISSUE THREAD

**Issue by tkosaka1976** [icalendar/icalendar#141]
I'd like to parse .ics file from reminder of macosx.
The file includes several to do list.

I parsed the .ics file via Icalendar.parse
Then I got Icalender::Todo class object

But I can not figure out how to get the list data from the object.
If I use p command to see the contents as:

    #<Icalendar::Todo:0x007f8754835be8 @name="todo", @ical_name="VTODO", @custom_components={}, @custom_properties={}, @dtstamp=#<DateTime: 2016-01-16T05:39:12+00:00 ((2457404j,20352s,796390000n),+0s,2299161j)>, @uid="b0f20490-4471-46a4-a12b-ac592ae9b185", @parent=#<Icalendar::Calendar:0x007f87540990b0 @name="calendar", @ical_name="VCALENDAR", @custom_components={}, @custom_properties={}, @prodid="-//Apple Inc.//Mac OS X 10.11.2//EN", @version="2.0", @calscale="GREGORIAN", @todos=[#<Icalendar::Todo:0x007f87540a1b98 @name="todo", @ical_name="VTODO", @custom_components={}, @custom_properties={}, @dtstamp=#<DateTime: 2015-08-17T01:44:39+00:00 ((2457252j,6279s,0n),+0s,2299161j)>, @uid="12EBCE25-3518-4E1C-9D97-7569EF3D8C97", @sequence=0, @summary="図を作る", @created=#<DateTime: 2015-08-17T01:44:39+00:00 ((2457252j,6279s,0n),+0s,2299161j)>, @parent=#<Icalendar::Calendar:0x007f87540990b0 ...>>, #<Icalendar::Todo:0x007f87540a8128 @name="todo", @ical_name="VTODO", @custom_components={}, @custom_properties={"x_apple_sort_order"=>["461468677"]}, @dtstamp=#<DateTime: 2015-08-17T01:44:50+00:00 ((2457252j,6290s,0n),+0s,2299161j)>, @uid="D9B50AB3-E2CD-46BC-AC60-87AAFD20135A", @sequence=0, @summary="文章を練る", @created=#<DateTime: 2015-08-17T01:44:50+00:00 ((2457252j,6290s,0n),+0s,2299161j)>, @parent=#<Icalendar::Calendar:0x007f87540990b0 ...>>, #<Icalendar::Todo:0x007f875485cb08 @name="todo", @ical_name="VTODO", @custom_components={}, @custom_properties={}, @dtstamp=#<DateTime: 2015-08-17T01:44:36+00:00 ((2457252j,6276s,0n),+0s,2299161j)>, @uid="B2079434-7B74-4B5F-88AC-3C3C09398BCD", @sequence=0, @summary="まず文章で全体を構築", @created=#<DateTime: 2015-08-17T01:44:36+00:00 ((2457252j,6276s,0n),+0s,2299161j)>, @parent=#<Icalendar::Calendar:0x007f87540990b0 ...>>, #<Icalendar::Todo:0x007f8754835be8 ...>]>>

I hope to use each method or directly to convert the list to Array object.
How to do this?

**Comment by rahearn** [comment]
Can you share the source ics file?

**Comment by rahearn** [comment]
Closing due to lack of followup
