### ISSUE TITLE
Parsing of dtstart/dtend with VALUE=DATE does not parse time

### ISSUE THREAD

**Issue by gavk34** [icalendar/icalendar#144]
I have the below ics file

If I try to parse this file and retrieve the dtstart and dtend parameters I get the following output
event.dtstart
Sat, 25 Jan 2020
event.dtend
Sat, 25 Jan 2020

As you can see there is no time outputted. Am I missing something or is it possible that the DTSTART;VALUE=DATE:20200125T150000Z with VALUE+DATE is causing the time not to be parsed? Thanks. Great gem by the way!!!

```
BEGIN:VCALENDAR
PRODID:-//Ben Fortuna//iCal4j 1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20160301T145438Z
DTSTART;VALUE=DATE:20200125T150000Z
SUMMARY:AutoTest Calendar Event
DTEND;VALUE=DATE:20200125T170000Z
LOCATION:
DESCRIPTION: Awesome Event
UID:xxxxxxxxx
END:VEVENT
END:VCALENDAR
```

**Comment by gavk34** [comment]
Never mind you can close this. It is an issue with our ICS file :) I kinda answered my issue above, the VALUE=DATE means only the date will be used where as if I can change this to VALUE=TIME I get the full parse of the datetime. Thanks

**Comment by espen** [comment]
Time is just time for date and time you want to use date-time. See https://tools.ietf.org/html/rfc5545#section-3.3.5
