### ISSUE TITLE
Access the RRULE value?

### ISSUE THREAD

**Issue by MattMencel** [icalendar/icalendar#145]
How do I access the RRULE string value?

When I print it out it appears as an OpenStruct object.  There isn't a to_s method that I can find.  Is there another way?

This:
`FREQ=YEARLY;BYMONTHDAY=15;BYMONTH=9`

Instead of this:
`<OpenStruct frequency=\"YEARLY\", until=nil, count=nil, interval=nil, by_second=nil, by_minute=nil, by_hour=nil, by_day=nil, by_month_day=[\"15\"], by_year_day=nil, by_week_number=nil, by_month=[9], by_set_position=nil, week_start=nil>`

Thanks,
Matt

**Comment by rahearn** [comment]
try `#value_ical`

**Comment by MattMencel** [comment]
Thanks!
