### ISSUE TITLE
Timezones with GMT Offsets Fail to Match

### ISSUE THREAD

**Issue by masonwash** [icalendar/icalendar#147]
Ical feeds from Microsoft often include a GMT offset at the start and these fail because Icalendar can't match the timezone: 

Unknown TZID specified in ical event ("(GMT-05:00) Eastern Time (US & Canada)"), ignoring (will likely cause event to be at wrong time!)

If I strip off the GMT offset clause first, then everything is fine.  Is there a way to tell Icalendar to do this?  If not are there plans to handle this in the future?

**Comment by espen** [comment]
Can you put up a gist with an ical feed that has this issue?

**Comment by masonwash** [comment]
https://gist.github.com/masonwash/5d0092740f2889cedf1c318dfe9d4d3c

the error happens when using recurrence to expand out the series

the event that causes the problem starts on line 65

**Comment by rahearn** [comment]
This should be fixed by #191
