### ISSUE TITLE
Adding the timezone from an ActiveSupport::TimeZone / TZInfo::DataTimezone

### ISSUE THREAD

**Issue by Startouf** [icalendar/icalendar#150]
I've read the various issues about timezones (including #128 ) but I cannot figure out how to input the tzinfo correctly.

I am using rails `time_zone` helper that generates ActiveSupport timezone string like 'Paris' (not prefixed by the area), so I am converting back to tzinfo but I still run into errors.

```ruby
ical = Icalendar::Calendar.new
require 'tzinfo' unless defined?(::TZInfo)

appointment.time_zone # => "Paris"
tz = ActiveSupport::TimeZone.new(appointment.time_zone).tzinfo.name # => #<TZInfo::DataTimezone: Europe/Paris>
timezone = tz.ical_timezone appointment.from 
# => *** NoMethodError Exception: undefined method `ical_timezone' for #<TZInfo::DataTimezone: Europe/Prague>
```

Rails 5.0.0rc1
tzinfo (1.2.2)
icalendar (2.3.0)

**Comment by espen** [comment]
Try:

```ruby
tz = ActiveSupport::TimeZone.new("Paris").tzinfo # => #<TZInfo::DataTimezone: Europe/Paris>
timezone = tz.ical_timezone Time.zone.now
```

**Comment by Startouf** [comment]
@espen 
`timezone = tz.ical_timezone Time.zone.now`
> NoMethodError: undefined method `ical_timezone' for #<TZInfo::DataTimezone: Europe/Paris>

**Comment by espen** [comment]
Which version of rails, tzinfo and icalendar are you using?

**Comment by espen** [comment]
Rails 5 (RC) seems to return TZInfo::DataTimezone instead of TZInfo::TimezoneProxy for ```ActiveSupport::TimeZone.new("Paris").tzinfo```

**Comment by espen** [comment]
```require 'icalendar/tzinfo'``` is required. Search the readme for 'tzinfo' for more info.

**Comment by Startouf** [comment]
Sorry, I had missed that line of the readme.
