### ISSUE TITLE
Undefined Method 'multiple_properties'

### ISSUE THREAD

**Issue by jfeldstein** [icalendar/icalendar#164]
When parsing https://calendar.google.com/calendar/ical/kiddom.co_l6t4eirk3cj7teme3mtjmb2eoc%40group.calendar.google.com/public/basic.ics

I get: 

![screen shot 2016-09-15 at 12 37 39 pm](https://cloud.githubusercontent.com/assets/172683/18564628/3a49e948-7b41-11e6-8d97-a498d87eb74f.png)

**Comment by espen** [comment]
I'm able to parse this URL. Can you provide a failing test for this?

**Comment by rahearn** [comment]
Closing after no OP followup
