### ISSUE TITLE
Custom Property

### ISSUE THREAD

**Issue by kripadas** [icalendar/icalendar#169]
How can i use custom property?
like this? x_test_value = "some value"

Is this possible to display this custom value in ios calendar?

**Comment by espen** [comment]
Yes, that's how you use it. Normal calendar applications, including iOS Calendar, doesn't display arbitrary custom values.

**Comment by kripadask** [comment]
Thanks **Espen**

**Comment by kripadas** [comment]
Thanks **Espen**

**Comment by espen** [comment]
Can you please close this issue if that answered your question.
