### ISSUE TITLE
TZInfo::AmbiguousTime when using ical_timezone

### ISSUE THREAD

**Issue by espen** [icalendar/icalendar#172]
So DST dropped by and I noticed some errors in my application during the transition. I'm not sure if this is an error on my end, in ical_timezone or tzinfo but as it originates from ical_timezone I'm opening an issue here.

Basically the code that fails is this:

``` ruby
require "icalendar"
require "tzinfo"
require "icalendar/tzinfo"

zone = "Europe/Stockholm"
t = Time.local(2016, 10, 30, 02, 54)
TZInfo::Timezone.get(zone).ical_timezone(t)
```

resulting in

``` shell
TZInfo::AmbiguousTime: 2016-10-30 02:54:00 +0100 is an ambiguous local time.
    from /tzinfo-1.2.2/lib/tzinfo/timezone.rb:415:in `period_for_local'
    from /icalendar-2.4.1/lib/icalendar/tzinfo.rb:95:in `ical_timezone
```

Setting the DST param to true/false for ical_timezone works (the default is nil).

**Comment by chamnap** [comment]
I got it as well on the feature spec. It failed randomly.

> Failure/Error: calendar.add_timezone(time_zone.ical_timezone(created_at))
     
>     TZInfo::AmbiguousTime:
       2016-11-06 01:57:09 -0800 is an ambiguous local time.

**Comment by espen** [comment]
I'm looking into ways of ical_timezone using the dst value from the date object if it can. Currently it seems like this will break current behaviour though. Anyone has any input here?

So something like:
  ```ruby
if date.respond_to?(:dst?)
 dst = date.dst?
else
  dst = Timezone.default_dst
end
```

**Comment by petrsigut** [comment]
Happens to us always when Summer time/Daylight saving time is changing😇

**Comment by juliannaroen** [comment]
@espen @petrsigut The [`TZInfo::TimeZone#ical_timezone` documentation doesn't specify it](https://www.rubydoc.info/gems/icalendar/1.4.0/TZInfo/Timezone:ical_timezone), but you can pass a second boolean argument to `ical_timezone` to specify whether daylight savings time or local time should be used in ambiguous cases. See the [source code for `TZInfo::TimeZone#ical_timezone`](https://github.com/icalendar/icalendar/blob/ebe950c939d05898adda418c6449005542ba5556/lib/icalendar/tzinfo.rb#L94) and [docs on `TZInfo::Timezone#period_for_local`](https://www.rubydoc.info/gems/tzinfo/0.3.51/TZInfo%2FTimezone:period_for_local).

**Comment by espen** [comment]
@juliannaroen yes that is actually what I am using in my own code: ´ical_timezone(Time.zone.now, Time.zone.now.dst?)´. But I don't think it should be necessary to specify it at all like in https://github.com/icalendar/icalendar/issues/172#issuecomment-258736938

**Comment by rahearn** [comment]
I believe you could achieve your goal from https://github.com/icalendar/icalendar/issues/172#issuecomment-258736938 by just setting `Timezone.default_dst = false` or always passing `false` to `ical_timezone`

It appears that when I create Time.new in ambiguous local times it defaults to the standard time version (`dst?` returns false).  In any case, for the same reason that `period_for_local` doesn't have a default value that assumes it knows which period is accurate, I don't think it is icalendar's place to know the right answer either.
