### ISSUE TITLE
License in gemspec is missing

### ISSUE THREAD

**Issue by reiz** [icalendar/icalendar#176]
What is the license of this package? Can you please provide the license in the gemspec? 

In the Copying file I have read that you want to provide 3 licenses, GPL, BSD and Ruby. Please pick one to avoid confusion. The GPL license says that I have to open source my code as well if I use a GPL dependency. With the BSD license I don't have to do that. So which license is now valid for this package? I'm confused!

**Comment by rahearn** [comment]
Closed by #254
