### ISSUE TITLE
Invalid DTSTAMP with rails 4.2.8

### ISSUE THREAD

**Issue by JohnColvin** [icalendar/icalendar#177]
We're using the 1.x branch and we started to have issues with invalid DTSTAMP when we updated to rails 4.2.8. I believe due to this change in rails:

> the internal time value in ActiveSupport::TimeWithZone is now always an instance of Time in the UTC timezone

https://github.com/rails/rails/blob/v4.2.8/activesupport/CHANGELOG.md

We're getting DTSTAMPs that are just HHMMSS. I believe it's due to the `to_ical` method implemented on time here https://github.com/icalendar/icalendar/blob/1.x/lib/icalendar/conversions.rb#L95

```ruby
class Time
  attr_accessor :ical_params
  def to_ical(utc = false)
    s = strftime '%H%M%S'

    # UTC time gets a Z suffix
    if utc
      s << "Z"
    end

    s
  end
end
```

I'm not sure how to properly patch the gem to handle this change. For our use we don't need plain time representations, so we may use our own fork of 1.x where `Time#to_ical` returns a full date time stamp.

Thanks for the help!

**Comment by espen** [comment]
I'm unable to replicate this in Rails 5. Can you provide a failing test?

**Comment by JohnColvin** [comment]
I was able to track this down to a line in our code where we were forcing DTSTAMP to utc, which was causing the issue

```
Icalendar::Event.new.tap do |event|
  ...
  event.dtstamp = event.dtstamp.utc
  ...
end
```

Removing this line fixes the issue. Thanks for looking into this!

**Comment by espen** [comment]
Great.

btw in most cases you want dtstamp to be generated by icalendar as this attribute is not when the event was created but when it was generated in the icalendar file. So in most cases this should be the current timestamp.

> This property is different than the "CREATED" and "LAST-MODIFIED" properties. These two properties are used to specify when the particular calendar data in the calendar store was created and last modified. This is different than when the iCalendar object representation of the calendar service information was created or last modified.

See http://www.kanzaki.com/docs/ical/dtstamp.html
