### ISSUE TITLE
Missing property

### ISSUE THREAD

**Issue by MrLinker** [icalendar/icalendar#178]
The 'related-to' property seems to be missing. When encountered it raises a NoMethodError in the parse_property method inside parser.rb.
`WARN -- : No method "related_to=" for component #Icalendar::Alarm:0x007fe58eb536e8. Appending to custom.`

**Comment by espen** [comment]
RELATED-TO was present in VALARM before a rewrite: https://github.com/icalendar/icalendar/commit/1040a6e66bd6b00ba85b025e7725992fe4bee546#diff-dd61e8251dee9aeaed8d844bbc4bea4cR37

It doesn't seem to be part of the spec for VALARM, so I guess that is why it was removed: 

> [The property can be specified one or more times in the "VEVENT", "VTODO" or "VJOURNAL" calendar components.](http://www.kanzaki.com/docs/ical/relatedTo.html)
