### ISSUE TITLE
Request: support for tasks ("todos")

### ISSUE THREAD

**Issue by brandondrew** [icalendar/icalendar#180]
Unless I'm missing something, this does not appear to support tasks:
https://github.com/icalendar/icalendar/search?utf8=%E2%9C%93&q=VTODO&type=

Such support would be useful.  Thank you.

**Comment by jhubert** [comment]
@brandondrew There is support. The VTODO value is generated instead of written in the code. Check out https://github.com/icalendar/icalendar/blob/master/lib/icalendar/todo.rb

**Comment by smcabrera** [comment]
It looks like this can be closed since the requested functionality is already supported?
