### ISSUE TITLE
undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by Davidzhu001** [icalendar/icalendar#181]
![image](https://user-images.githubusercontent.com/9436230/28178346-ce095f14-67c3-11e7-8d84-25a518c9b7bf.png)

**Comment by espen** [comment]
What is Ical here?

Have you looked at the readme for how to create an icalendar object and attach an event to it?

Can you provide a failing test for this?

**Comment by Davidzhu001** [comment]
it was my problem, sorry
