### ISSUE TITLE
Received "NameError: wrong constant name Text/html" while parsing ics from Windows Phone

### ISSUE THREAD

**Issue by echetzakis** [icalendar/icalendar#182]
Parsing an ics results in "NameError: wrong constant name Text/html"
due to the following field:
```
X-ALT-DESC;VALUE=text/html:<!DOCTYPE html PUBLIC ...*
```
_*: rest of the html content omitted from this snippet_ 

The ics was sent from a Windows Phone as the `PRODID:Microsoft Windows Phone` indicates.

**Comment by espen** [comment]
I don't think that is valid. text/html isn't a [value type](https://tools.ietf.org/html/rfc5545#section-3.3). It can used when referenced as [ALTREP](https://tools.ietf.org/html/rfc5545#section-3.2.1) though.

**Comment by echetzakis** [comment]
Thanks for the reply, since this seems to be a **quirk** of the _Windows Phone Client_, we'll pre-process the ICS content before Parsing it.
