### ISSUE TITLE
Meeting not added to Attendee calendar

### ISSUE THREAD

**Issue by Basikb110** [icalendar/icalendar#184]
I'm trying to add meetings to people within my organisation using .ics file. I'm using the following code:

ORGANIZER;CN=Test:mailto:test@test.com
ATTENDEE;CN=Test Person;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED:mailto:test@testperson.com

For some reasons meetings are added only to my calendar, which shouldn't happen as I'm only Organiser. The meeting is not visible in the Attendee calendar. Weird thing is that when I go to the scheduling assistant the Attendee is displayed correctly.
Have any of you ever experienced similar issue or do you have the idea how this can be resolved?

**Comment by espen** [comment]
Is this an issue with the icalendar gem? If not then perhaps try asking on StackOverflow?

**Comment by rahearn** [comment]
I'm not sure how this relates to the icalendar gem. Please reopen with more details if I'm wrong. Otherwise, I agree that StackOverflow would be a better forum to ask the question.
