### ISSUE TITLE
RFC7986 new properties - support for name property

### ISSUE THREAD

**Issue by espen** [icalendar/icalendar#193]
I want to add the new calendar properties from [RFC7986](https://tools.ietf.org/html/rfc7986), however it seems to be a problem with adding a `name` property due to it being an attribute of `component`. Any suggestions on how to solve this?

See https://github.com/espen/icalendar/blob/rfc7986/lib/icalendar/calendar.rb

**Comment by rahearn** [comment]
You could call it `ip_name` similar to how we handle the `method` and `class` properties. That list of special handling names [leaks into the parser](https://github.com/icalendar/icalendar/blob/master/lib/icalendar/parser.rb#L36) as well so if you wanted to clean that up at the same time it'd be wonderful.

**Comment by espen** [comment]
Ah, didn't notice that even though it was on the line above 😅

Added in https://github.com/icalendar/icalendar/pull/198

Thanks for the info!
