### ISSUE TITLE
How to specify an event as "Free"

### ISSUE THREAD

**Issue by cromulus** [icalendar/icalendar#201]
I'm trying to export a calendar which has events that should be able to be booked over. Ideally, I'd like those events to be marked "Free". I've looked at the [freebusy](https://github.com/icalendar/icalendar/blob/master/lib/icalendar/freebusy.rb) implementation and I'm not quite sure how you specify an event as free and/or tentative.

Thanks!

**Comment by arcreative** [comment]
Same issue... would love to set the property in an idiomatic way, but I think I'm going to have to tinker with monkey patching the event class...

**Comment by arcreative** [comment]
@cromulus I haven't really checked the ics spec yet for whether or not this is valid, but you can do the following in `config/initializers/icalendar.rb` (assuming you're using Rails).  You might want to do a module extension, but I'm tired of messing with it for now :-)

```ruby
Icalendar::Event.class_eval do
  optional_single_property :freebusy, Icalendar::Values::Text
  optional_single_property :x_microsoft_cdo_busystatus, Icalendar::Values::Text
end
```

**Comment by arcreative** [comment]
Per this SO link: https://stackoverflow.com/questions/798016/vcalendar-show-as-free-busy-tentative-out-of-office

it looks like the spec for freebusy is a little different, so I'm just going to omit it for now, as most of our users use Outlook.

**Comment by espen** [comment]
An event is an occupied event, not an available slot. Using VEVENT would not be suitable. VFREEBUSY is what to use and to set FBTYPE=FREE.

> A "VFREEBUSY" calendar component is a grouping of component properties that represents either a request for, a reply to a request for free or busy time information or a **published set of busy time information**.

> Free/Busy information is represented with the "FREEBUSY" property.

See https://www.kanzaki.com/docs/ical/vfreebusy.html and https://www.kanzaki.com/docs/ical/freebusy.html

Not sure how many clients support this or if it is practical to use it across apps though.

**Comment by arcreative** [comment]
@espen Hmm, thanks.  I was able to solve this for our use case by just using `X-MICROSOFT-CDO-BUSYSTATUS:FREE`, but that's good to know for future reference.  Seems like the event spec doesn't support all the needed features :-)

**Comment by rahearn** [comment]
There doesn't seem to be much to do here, so I'm closing this issue.

FWIW, [Time Transparency](https://tools.ietf.org/html/rfc5545#section-3.8.2.7) is what is used to mark an event as free, though other calendar clients won't treat that time as opportunities for booking, so I'm not sure it'll work for your described use case unless you are controlling both server and client side. And if you control both sides you can just use whatever `X-` custom attribute you want.
