### ISSUE TITLE
Exception when setting timezones with frozen strings

### ISSUE THREAD

**Issue by CHTJonas** [icalendar/icalendar#209]
Hi 👋 love the gem! However using with the `# frozen_string_literal: true` magic comment raises a `FrozenError` on runtime. For clarity the following seems to reproduce the issue with a modern Ruby version eg. 2.6.1:
```ruby
cal = Icalendar::Calendar.new
cal.timezone do |t|
  t.tzid = 'Europe/London'.freeze
  t.daylight do |d|
    d.tzoffsetfrom = '+0000'.freeze
    d.tzoffsetto   = '+0100'.freeze
    d.tzname       = 'BST'.freeze
    d.dtstart      = '19810329T010000'.freeze
    d.rrule        = 'FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU'.freeze
  end
  t.standard do |s|
    s.tzoffsetfrom = '+0100'.freeze
    s.tzoffsetto   = '+0000'.freeze
    s.tzname       = 'GMT'.freeze
    s.dtstart      = '19961027T020000'.freeze
    s.rrule        = 'FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU'.freeze
  end
end
```

This is the line of code that appears to be the issue (there could be others - I haven't done much digging):
https://github.com/icalendar/icalendar/blob/5214946568655f3355a8b61179277becf2d52334/lib/icalendar/values/utc_offset.rb#L40

**Comment by rahearn** [comment]
@CHTJonas I believe this has been fixed on master now. I'd love if you could give it a test if you're still using the gem.

**Comment by CHTJonas** [comment]
@rahearn thank so much for that - seems to be working nicely now! 😄

Is there any chance of a release with this included? 🚀

**Comment by rahearn** [comment]
2.6.0 released including this.
