### ISSUE TITLE
EXDATE is parsed as a two-dimensional array 

### ISSUE THREAD

**Issue by AmenZhou** [icalendar/icalendar#210]
I found something wrong with parsing recurrence events with EXDATE. The parsed EXDATE is a two-dimensional array when there are more than one EXDATE in the ics file.

e.g.

I use one of the fixture files in this repo. Parse [this](https://github.com/icalendar/icalendar/blob/master/spec/fixtures/recurrence.ics) ics file, there are two exdates in the file.

```ruby
cal = Icalendar::Calendar.parse(File.read("recurrence.ics")).first
event = cal.events.first
event.exdate
#=> [[Fri, 23 Mar 2012, Sat, 23 Mar 2013]]
``` 
The outer array is an `Array`, the inner array is an `Icalendar::Values::Array`. It only happens when there are more than 1 EXDATE in the ics.

I realized it is an issue when I call `event.occurrences_between` on the parsed event, it raises an exception referring to the wrong time type.

I haven't dig into the code yet. I will post updates if I find the root cause later. 

### Updates:
I found this related open [issue](https://github.com/icalendar/icalendar-recurrence/pull/21) in icalendar-recurrence repo.

I guess that having 2 inconsistent `exdate` types between one EXDATE and more than one EXDATE is expected. But I feel it is not ideal.

**Comment by rahearn** [comment]
The underlying issue with `occurrences_between` has been fixed in icalendar-recurrence v1.1.3. I agree that the arrays thing is weird, but that won't be tackled right now as it would be a breaking change.
