### ISSUE TITLE
RFC7986 Support

### ISSUE THREAD

**Issue by EnrightArthrex** [icalendar/icalendar#227]
Not an issue per se my apologies, any thoughts on when RFC7986 support may be added?

**Comment by espen** [comment]
There has been some work done here: https://github.com/icalendar/icalendar/pull/198

Feel free to progress with it.

**Comment by espen** [comment]
Is this implemented or why was it closed @rahearn ?

**Comment by rahearn** [comment]
#198 is still open and tracking this work. I closed this as a duplicate
