### ISSUE TITLE
Need clearification with this gem

### ISSUE THREAD

**Issue by RohitVenturit** [icalendar/icalendar#228]
Hi Team, I want to get detailed information about this gem. I can see this gem can create ics files but How I can publish or add events into the Apple calendar for the current user who is logged in?

**Comment by espen** [comment]
Please see the [examples](https://github.com/icalendar/icalendar#examples
) in the documentation.

If you have any further questions I suggest posting at [StackOverflow](https://stackoverflow.com).

**Comment by rahearn** [comment]
Hi @RohitVenturit, this gem only deals with parsing and generating ics files. Integration with calendar services is outside of the scope and I also suggest trying StackOverflow.
