### ISSUE TITLE
Unable to RSVP - Add to calendar shows up instead (works after manually making changes to the generated ics file)

### ISSUE THREAD

**Issue by febincloudyuga** [icalendar/icalendar#229]
For some reason in Google Calendar, participants do not receive "Yes, No, Maybe" RSVP buttons when they receive an invitation from few hosts(works for email addresses of some hosts).
I'm not able to find a pattern, but for a few emails as organizers, what shows up is "Add to Calendar" and not the RSVP buttons.
![image](https://user-images.githubusercontent.com/29917673/77517111-91047580-6ea1-11ea-94f6-c5238db55ad6.png)

This is my code
```
def generate_ical
  ical = Icalendar::Calendar.new
  event = Icalendar::Event.new
  event.dtstart = Icalendar::Values::DateTime.new @event_start
  event.location = @location
  event.organizer = @organizer
  event.summary = @subject
  ical.add_event(event)
  ical.append_custom_property('METHOD', 'REQUEST')
  ical
end
```
[After googling around a bit](https://support.google.com/calendar/thread/658334?hl=en), I could see this Calendar related issue was faced by a few other users also, but there isn't any solution yet.

What I did next was to manually create an invitation via Calendar. In this case, the buttons showed up.

Next, I made a comparison between the ics file generated by this Gem and the one from the invitation I manually created

I could see there was a field called ATTENDEE in the calendar generated file

`ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=febin@example.come;X-NUM-GUESTS=0:mailto:febin@example.com`

**Here, notice the ";" after ATTENDEE**

So I went ahead and added this line of code
`event.attendee = "CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=febin@cloudyuga.guru;X-NUM-GUESTS=0:mailto:febin@cloudyuga.guru"`

In the Gem generated ics file, the below line was added, but I  still wasn't able to see the RSVP buttons
`ATTENDEE:CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 TRUE;CN=febin@cloudyuga.guru;X-NUM-GUESTS=0:mailto:febin@cloudyuga.guru`

**Notice here the ':' after ATTENDEE**

**Next what I did is to modify `:` to `;` manually, and sent an email by attaching this file and that showed up the RSVP buttons**

![image](https://user-images.githubusercontent.com/29917673/77517154-a11c5500-6ea1-11ea-8e41-e827ed767bb4.png)

If I've done it the right way, can this change be introduced in this gem?

**Comment by espen** [comment]
It might be due to putting ical values directly like that. Try using the value helpers:

```ruby
 event.append_attendee Icalendar::Values::CalAddress.new("mailto:foo@example.org",
          'CUTYPE' => 'INDIVIDUAL',
          'ROLE' => 'REQ-PARTICIPANT',
          'CN' => "Foo",
          'X-NUM-GUESTS' => 1,
          'PARTSTAT' => 'TENTATIVE'
        )
```

(just example above, not sure about which settings do use in your case)

**Comment by febincloudyuga** [comment]
That worked. Thank you very much.
