### ISSUE TITLE
`Add to google calendar` link not showing in gmail

### ISSUE THREAD

**Issue by wxxiao33** [icalendar/icalendar#231]
I set up the mailer as following:
```
class ChallengeMailer < ApplicationMailer
  def new_challenge_email
    @challenge = params[:challenge]
    @user = params[:user]

    cal = Icalendar::Calendar.new
    cal.timezone.tzid = "UTC"           
    event = Icalendar::Event.new
    event.dtstart = @challenge.deadline.days_ago(@challenge.duration)
    event.dtend = @challenge.deadline
    event.organizer = 'Organizer'
    event.summary = @challenge.name
    event.description = @challenge.description
    event.url = challenge_url(@challenge)
    cal.add_event(event)            
    cal.publish
    mail.attachments['challenge_cal.ics'] = { :mime_type => 'text/calendar', content: cal.to_ical }
    mail(to: @user.email, subject: @challenge.name)
  end
end
```
But when I receive this email, I can see the details of the calendar in my Gmail, but there is no `add to google calendar` link. 
![image](https://user-images.githubusercontent.com/43286868/81351306-ff884600-9091-11ea-9a50-694a3342ad7b.png)

For now, I had to import the .ics file manually. How could I get the add to calendar link in Gmail?
Also, what should I do if I want my email to be shown in "Who"?

**Comment by matthieua** [comment]
I have the exact same problem here 😢

**Comment by espen** [comment]
Google Calendar has changed how they add events over the recent years. Try adding a status. You might also need to add the receiver as an attendee with partstat. The organizer field is also invalid, you should use Icalendar::Values::CalAddress.new to set it.

Regardless, this is not an issue with this gem. Try asking on StackOverflow.

**Comment by wxxiao33** [comment]
> I have the exact same problem here 😢

Add attendee like this solves my problem
`event.attendee = Icalendar::Values::CalAddress.new("mailto:#{@user.email}", cn: "#{@user.name}")`

**Comment by emilkarl** [comment]
> > I have the exact same problem here 😢
> 
> Adding attendee and organizer like this solves my problem `event.attendee = Icalendar::Values::CalAddress.new("mailto:#{@user.email}", cn: "#{@user.name}")` `event.organizer = Icalendar::Values::CalAddress.new("mailto:foo@example.com", cn: "#{@challenge.name}")`

Do you need the organizer for this to work?
