### ISSUE TITLE
Multiline description / email body

### ISSUE THREAD

**Issue by nimeshnikum** [icalendar/icalendar#242]
iCalendar events work proper for me, except one issue with invitation notes. From the documentation, I figured out that I can use `description` and set the desired text there. This works nice for a single-line text, but doesn't work with multi-line text or parse correctly. Can someone please suggest what could be the best solution?

Following is my sample code:
```
def to_ical
    tz = ActiveSupport::TimeZone.new(timezone).tzinfo
    c = Icalendar::Calendar.new
    c.add_timezone(tz.ical_timezone(Time.now))
    c.event do |e|
      e.dtstart = start_datetime_for_display
      e.dtend = end_datetime_for_display
      e.summary = "Invitation summary..."
      e.description = "Thank you for registering to the event. Please find venue details below: \n Date: <date> \n Time: <time> \n Location: <Location>"
    end
    c.to_ical
  end
```

I want output in this format:

Thank you for registering to the event. Please find venue details below:
**Date**: <<date_value>>
**Time**: <<time_value>>
**Location**: <<location_text>>

**Comment by rahearn** [comment]
Where are you trying to display the description? We just hold text so there's not much I can offer you in terms of formatting output if what you've shared isn't working.

**Comment by rahearn** [comment]
Closing due to no response.

**Comment by espen** [comment]
@nimeshnikum [perhaps try \\n or \r\n](https://stackoverflow.com/questions/666929/encoding-newlines-in-ical-files)

**Comment by nimeshatpair** [comment]
@espen Thanks, that worked!
