### ISSUE TITLE
Update documentation for `TZInfo::Timezone#ical_timezone`

### ISSUE THREAD

**Issue by juliannaroen** [icalendar/icalendar#243]
The `TZInfo::Timezone#ical_timezone` method accepts a second parameter which specifies whether to use DST or local time in ambiguous time cases ([see source](https://github.com/icalendar/icalendar/blob/ebe950c939d05898adda418c6449005542ba5556/lib/icalendar/tzinfo.rb#L94)).

The [documentation for this method](https://www.rubydoc.info/gems/icalendar/1.4.0/TZInfo/Timezone:ical_timezone) does not acknowledge this second parameter and should be updated to do so.

See [`TZInfo::Timezone#period_for_local` documentation](https://www.rubydoc.info/gems/tzinfo/0.3.51/TZInfo%2FTimezone:period_for_local) as a reference for how this second parameter can be explained.

**Comment by espen** [comment]
Looks like the code in the doc is outdated? Which seems odd.

**Comment by rahearn** [comment]
That was the old 1.x version on RubyDoc.
