### ISSUE TITLE
Error when generating `ical_timezone` with UTC timezone on Linux after upgrading to tzinfo 2.x

### ISSUE THREAD

**Issue by f1sherman** [icalendar/icalendar#246]
Hi there! I noticed that after upgrading to `tzinfo` 2.x from 1.x that doing something like the following fails on Linux:
```
> ActiveSupport::TimeZone.new('UTC').tzinfo.ical_timezone(Time.current)

Icalendar::Values::DateTime::FormatError: Failed to parse "-182669369710819T170152" - invalid date
from /root/.rbenv/versions/2.7.2/lib/ruby/2.7.0/delegate.rb:85:in `bind_call'
Caused by Date::Error: invalid date
from /app/vendor/bundle/ruby/2.7.0/gems/icalendar-2.7.0/lib/icalendar/values/date_time.rb:17:in `strptime'
```

I'm not seeing the same error on MacOS. It appears that the `dtstart` for the UTC start period on Linux now returns `"-182669369710819T170152"`, where in tzinfo 1.x it returned `"17000101T000000"`.

Let me know if you could use any more info, thanks!

**Comment by lunohodov** [comment]
I had the same error popping up on CI (Linux) but not locally (MacOS).

A small change in the `Gemfile` solved it

```diff
- gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
+ gem "tzinfo-data"
```

**Comment by lowski** [comment]
Confirming that adding `gem "tzinfo-data"` solved problem for us on Heroku. I wasn't able to reproduce this error locally on Linux (Ubuntu 20.04).

**Comment by rahearn** [comment]
I added a note to README that `tzinfo-data` may be required. I don't think there's much else we can do to address this.

**Comment by anoobbava** [comment]
@rahearn  I know that this issue is closed, how about adding this gem as dependency for the icalendar,  I was struggling 2 days for this issue when uppgrading to 6.1. and this fix is working for me.
