### ISSUE TITLE
Icalendar is feeding something to ActiveSupport with a hash as keyword params

### ISSUE THREAD

**Issue by doriantaylor** [icalendar/icalendar#249]
Trying to parse/manipulate an `.ics` file and getting a stream of:

`/var/lib/gems/2.7.0/gems/activesupport-6.1.1/lib/active_support/core_ext/time/calculations.rb:46: warning: Using the last argument as keyword parameters is deprecated`

i.e., the Ruby 2.7+ deprecation of hashes being interpreted as keyword parameters. Since it's a warning I have no idea what's calling it, so unfortunately I need some guidance to be of more help than this.

**Comment by espen** [comment]
Could you show the code that is causing it?

**Comment by doriantaylor** [comment]
Ah, in attempting to isolate the behaviour it turns out to be a bug in ActiveSupport itself: elsewhere in the code I have the constructor `Time.at(epoch, in: utcoffset)` which appears to be wrapped by ActiveSupport which is pulled in by Icalendar. The former does not appear to account for this keyworded formulation.

Sorry to bother!
