### ISSUE TITLE
Support for RFC 7986 (Name, Color, Conference, Image, etc.)

### ISSUE THREAD

**Issue by Mange** [icalendar/icalendar#253]
[RFC 7986](https://tools.ietf.org/html/rfc7986) adds a lot of useful fields to icalendar which would be useful to have first-party support for in this gem.

**Comment by Mange** [comment]
For anyone else who wants to know how to use these fields right now, here's how I've been doing it:

```ruby
calendar.append_custom_property("name", "Example")
```

However, now I cannot parse in strict mode, and in either mode I get log rows about "name=" not being a method.

```
W, [2021-03-10T12:04:47.294298 #664]  WARN -- : No method "name=" for component #<Icalendar::Calendar:0x00007ff41df89bc0>. Appending to custom.
```

If this could be silenced, it would be great.

**Comment by espen** [comment]
See https://github.com/icalendar/icalendar/pull/198

Feel free to continue the work, I don't have to time to finish it right now.

**Comment by rahearn** [comment]
7986 support was added in #271
