### ISSUE TITLE
Accept invitation button not showing

### ISSUE THREAD

**Issue by sumitdey035** [icalendar/icalendar#255]
Here is an example of two .ics file which gets generated in the application.
```
$ cat -v ./invite_stuffed_124200.ics | head -n 6
BEGIN:VCALENDAR^M^M
VERSION:2.0^M^M
PRODID:auslan-booking-system^M^M
CALSCALE:GREGORIAN^M^M
METHOD:REQUEST^M^M
BEGIN:VTIMEZONE^M^M

$ cat -v ./invite_131404.ics | head -n 6
BEGIN:VCALENDAR^M
VERSION:2.0^M
PRODID:auslan-booking-system^M
CALSCALE:GREGORIAN^M
METHOD:REQUEST^M
BEGIN:VTIMEZONE^M
```
I don't know where the extra ^M is coming from, but the first one `invite_stuffed_124200.ics`, is not adding the invite in the calendar automatically. And in the mail, it appears as 
![image005](https://user-images.githubusercontent.com/6781218/113584908-2146d000-9649-11eb-9f4d-2f026b943056.png)

Where the 2nd one `invite_stuffed_131404.ics`, is working as expected.

And there are only a couple of users is getting this buggy .ics file randomly.

I am totally clueless here. ANy help?

**Comment by espen** [comment]
Google Calendar != icalendar. Unfortunately all calendar applications work a bit differently to how they handle event invitations and changes to events. And invites should not be added automatically, actually that was a problem before and it was used for invite spam.

Are there any other differences between these two events?

**Comment by sumitdey035** [comment]
> Google Calendar != icalendar. Unfortunately all calendar applications work a bit differently to how they handle event invitations and changes to events. And invites should not be added automatically, actually that was a problem before and it was used for invite spam.
> 
> Are there any other differences between these two events?

Actually, some of them are also facing in the iPhone calendar.
It used to show on the google calendar automatically they received an invite mail, but not happening that right now(2 users are complaining about it.)
Unfortunately, can't see any more difference between these two events.

**Comment by espen** [comment]
Could you show the entire ice, it is impossible to tell anything from the current sample.

**Comment by sumitdey035** [comment]
@espen here is the two files.
[invite_131404.txt](https://github.com/icalendar/icalendar/files/6347647/invite_131404.txt)
[invite_stuffed_124200.txt](https://github.com/icalendar/icalendar/files/6347648/invite_stuffed_124200.txt)

**Comment by espen** [comment]
@sumitdey035 I would it assume it doesn't make a difference but the second file has extra line breaks, did you try without? Also the first event is in the past, could it be that Google Calendar does not accept invitations in the past?

There also seems to be some lines that are longer than allowed. Check with https://icalendar.org/validator.html
