### ISSUE TITLE
Ability to "not" receive email based on RSVP status

### ISSUE THREAD

**Issue by chai2** [icalendar/icalendar#262]
Looking for ways on how to avoid an email alert to be not received based on customer Accept/Reject/MayBe an invitation.

Any insights? Thank you!

**Comment by espen** [comment]
Set it to false?

Ref https://www.kanzaki.com/docs/ical/rsvp.html

Regardless, this is not an issue with the icalendar gem so perhaps try StackOverflow to get an answer?

**Comment by chai2** [comment]
Great. Thanks for your suggestion. Will close the issue.
