### ISSUE TITLE
Handling Time Zone Changes

### ISSUE THREAD

**Issue by tfreedman** [icalendar/icalendar#263]
I just saw some messages in my error logs concerning the recent DST switchover, e.g.

```
TZInfo::AmbiguousTime: 2021-11-07 01:00:21 is an ambiguous local time
```

I looked over the code that triggered that (in case my logging code is buggy), but there seems to be some ambiguity in the documentation as for what you're correctly supposed to do in certain situations - namely, events where the start_time and end_time are at different UTC offsets as a result of DST. Here's some code that fails:

```
require "icalendar/tzinfo"
start_time = Time.parse('2021-11-07 01:30 -04:00') # Before clocks go back to 01:00
end_time = Time.parse('2021-11-07 01:30 -05:00') # After clocks have gone back

tzid = "America/Toronto" # Time.zone.name
tz = TZInfo::Timezone.get tzid

st = Time.at(start_time).to_datetime
et = Time.at(end_time).to_datetime

cal = Icalendar::Calendar.new
cal.add_timezone tz.ical_timezone Time.at(start_time), start_time.dst?

cal.event do |e|
  e.dtstart = Icalendar::Values::DateTime.new st, 'tzid' => tzid
  e.dtend = Icalendar::Values::DateTime.new et, 'tzid' => tzid
  e.uid = SecureRandom.uuid
  e.summary = "Test"
  e.sequence = 0
  e.transp = "OPAQUE"
  e.created = Time.now
end

x = cal.to_ical

y = Icalendar::Calendar.parse(x)[0]

puts y.events[0].dtstart
puts y.events[0].dtend

if y.events[0].dtstart == y.events[0].dtend
  raise "These times should not be equal"
end
```

**Comment by rahearn** [comment]
Yes. I'm not entirely sure what you're supposed to do in that situation, according to the icalendar spec. The error is exactly the problem. 1:30am on Nov 7, 2021 in the America/Toronto timezone happened twice (thus is ambiguous), and the spec doesn't really give a way (that I know of) of distinguishing which is which.

I'm all ears if anyone has a solution.

**Comment by hollandmatt** [comment]
We manage this by supplying `false` as the second param to `tz.ical_timezone`:

```
cal.add_timezone tz.ical_timezone Time.at(start_time), false
```

This will make it default to standard time if there's an ability. You can also do `true` to default to DST.
