### ISSUE TITLE
Specify REFRESH-INTERVAL

### ISSUE THREAD

**Issue by tbhockey** [icalendar/icalendar#272]
Is there any way to specify a `REFRESH-INTERVAL`? For example:

```
REFRESH-INTERVAL;VALUE=DURATION:PT24H
```

Searching through the repo, i cannot really find any mention of a `REFRESH-INTERVAL` aside from a test.
Thanks!

**Comment by espen** [comment]
```
ical.x_refresh_interval = 'PT15M'
```

**Comment by espen** [comment]
You can set any attribute using x_.

Actually it looks like `REFRESH-INTERVAL` has been added as a property: https://github.com/icalendar/icalendar/blob/main/lib/icalendar/calendar.rb#L14

So you can use `ical.refresh_interval`, but for other properties that are not added to this lib you can always use `x_prop`.

**Comment by tbhockey** [comment]
Thank you @espen ! 👌
