### ISSUE TITLE
icalendar can't handle timezones coming from Apple's iCloud .ical files

### ISSUE THREAD

**Issue by darrylo** [icalendar/icalendar#288]
.ical calendars can be downloaded from Apple's iCloud, and icalendar somehow can't handle the timezone infomration contained within them.    For example, despite the ical data for `DTSTART` being:

    DTSTART;TZID=America/Los_Angeles:20231025T163000

icalendar treats this as being in the UTC timezone.

Sample (redacted) .ics file: [raw.txt](https://github.com/icalendar/icalendar/files/13434597/raw.txt)

Test ruby script to show the bug:
```
require 'icalendar'

cals = Icalendar::Calendar.parse(File.open("raw.txt"))

first = cals.first
first.events.each { |e|
  #pp e
  print "dtstart = ", e.dtstart, "\n"
}
```
Running the script produces the incorrect timezone:
```
dtstart = 2023-10-25T16:30:00+00:00
```

**Comment by darrylo** [comment]
It's whatever version is installed via `gem install icalendar`:

    icalendar (2.10.0)

**Comment by darrylo** [comment]
OK, after much pain involving multiple versions of ruby, multiple versions of icalendar, two different windows boxes, and two different linux boxes, the problem is this:

### icalender does not work in a basic ruby installation

For the one case where icalendar did work, I coincidentally also happened to have the **ActiveSupport** gem installed.  This allowed "Plan A" to be used in `icalendar/lib/icalendar/values/helper/time_with_zone.rb`.  Without that (or plans B or C triggering), Plan D was used which completely **AND SILENTLY** ignored the time zone.

Plan D should probably be replaced by fugly unmentionables involving `::TZInfo::Timezone.get()` and sacrifices of aged roadkill.

So, the workaround is to install the `activesupport` gem.

**Gah**.

**Comment by rahearn** [comment]
@darrylo thanks for tracking this down. I'll see if we can't improve this somewhat. I think we hadn't done the `TZInfo` plan D route before because it's an optional dependency, but it's probably time to upgrade that to a runtime dependency so we can be more accurate. I'm also going to dig into why plan b didn't work for your example file.

**Comment by rahearn** [comment]
@darrylo if you're able to test the linked PR on windows, I'd appreciate it. I'm going to leave the PR open for a couple of days and test the branch out in a real app before merging.
