### ISSUE TITLE
Not Getting Gmail Response when i respond to "yes"

### ISSUE THREAD

**Issue by pragya-sriharsh** [icalendar/icalendar#295]
I am struggling with an issue where changing my response to an event invitation from "Yes" to "no" via Gmail does not send an email notification back to the vent organizer where both the sender and recipient are using Gmail. This problem does not occur if the sender is using a non-Gmail email service. 

Outlook to gmail- Works
Outlook to outlook - works
Gmail to outlook - works
Gmail to Gmail - not working

start_time_in_time_zone
<img width="459" alt="session_start_time" src="https://github.com/icalendar/icalendar/assets/118921874/751bf67f-7529-4503-b0cf-c4e13883e7c9">

end_time_in_time_zone
<img width="351" alt="session_end_date" src="https://github.com/icalendar/icalendar/assets/118921874/2f6f1911-d9a1-4536-a256-bb618a7075ce">

tz_info
<img width="354" alt="tz_info" src="https://github.com/icalendar/icalendar/assets/118921874/1c44f927-05ae-44d5-80e9-06d2547f5548">

My setting looks like: 

```
      def add_session_to_ical(session)
@ical_obj = Icalendar::Calendar.new
        start_time_in_time_zone = session.start_time_in_time_zone
        end_time_in_time_zone = session.end_time_in_time_zone
        tz_info = start_time_in_time_zone.time_zone.tzinfo
        
        @ical_obj.add_timezone(
          tz_info.ical_timezone(start_time_in_time_zone)
        )
  
        event = Icalendar::Event.new
        event.uid      = session.uuid
        event.sequence = Time.now.to_i
  
        event.dtstart = Icalendar::Values::DateTime.new(start_time_in_time_zone, tzid: "Asia/Kolkata")
        event.dtend   = Icalendar::Values::DateTime.new(, tzid: "Asia/Kolkata")
  
        event.location = "Pune"
        event.summary  = "My first event"
  
        event.alarm do |a|
          a.action  = "DISPLAY"
          a.description = "This is an event reminder"
          a.summary = "Event Notification"
          a.trigger = "-PT15M" # 15 minutes before
        end
  
        event.alarm do |a|
          a.action = "AUDIO"
          a.trigger = "-PT15M" # 15 minutes before
          a.append_attach "Breeze"
        end
  
        event.description = "Will update later"
        event.status = "CONFIRMED"
  
          event.organizer = Icalendar::Values::CalAddress.new(
            "MAILTO:p*****5@gmail.com",
            cn: "Prags"
          )
          event.attendee = Icalendar::Values::CalAddress.new(
            "MAILTO:s*****a@gmail.com",
            cn: "Sam",
            rsvp: true,
            partstat: "ACCEPTED" 
          )
        end
        @ical_obj.add_event(event)
    end
```

Let me know if required anything from my side.

**Comment by pragya-sriharsh** [comment]
@rahearn, Can you please look into it?

**Comment by rahearn** [comment]
The icalendar gem does not send any email, it simply parses and builds .ics format text. I don’t know why emails are being sent in some cases and not others.

**Comment by espen** [comment]
@pragya-sriharsh while icalendar is a standard not all clients implement it in the same way. For example how attendees, updates, and invites are treated in Gmail.
