### ISSUE TITLE
Incorrect Attendee parsing

### ISSUE THREAD

**Issue by kcore** [icalendar/icalendar#301]
My ICS file has the attendee data as follows - 
```ATTENDEE;CN=XXXXX;CUTYPE=INDIVIDUAL;EMAIL=XXXXXXXXXXXXX;PARTSTAT=ACCEPTED;X-CALENDARSERVER-```
```DTSTAMP=20181022T041700Z:/xxxxxxxxxxx/principal/```
and when I parse it, it returns attendee as an array of URI::Generic objects as follows -
```#<URI::Generic /XXXXXXX/principal/>```

Important Attributes like CN, Email, PARTSTAT are missed. Any idea what might be happening?

**Comment by rahearn** [comment]
Have you tried calling `ical_params` on that URI? If they're not there, please reopen this with a full ICS file that reproduces the issue and more information about what version of the library you're using

**Comment by kcore** [comment]
This worked! is there any documentation where we can update it so that others also benefit?
