### ISSUE TITLE
Not showing Accept/Decline/Tentative buttons with few mail clients.

### ISSUE THREAD

**Issue by srinatha** [icalendar/icalendar#31]
I am sending ics file as attachment with email and it was opening good in Gmail. 
However, i am facing issues with different mail clients.

I tried adding this property:
calendar.custom_property("METHOD", "REQUEST")

It was not showing Accept/Decline/Tentative buttons for Outlook,  Yahoo mail clients.

Do i need to add any more properties to detect  ?

Thanks in advance.

**Comment by andreasantillana** [comment]
Hi @danielfarrell, were you able to get the same behavior for the meeting organizer? I'm having trouble updating events for organizers.

**Comment by danielfarrell** [comment]
@andreasantillana I never did updating events over emails, sorry.
