### ISSUE TITLE
Alarms triggers lose data

### ISSUE THREAD

**Issue by dacook** [icalendar/icalendar#35]
According to RFC-2445, an alarm is by default relative to the event (or todo) start time, but it may also be:
- relative to the end time, eg:
  TRIGGER;RELATED=END:P5M
- an absolute date-time eg:
  TRIGGER;VALUE=DATE-TIME:19980101T050000Z

http://www.kanzaki.com/docs/ical/trigger.html

In these cases, the parser strips out the extra parameters. In order words, anything between the semi-colon and colon is lost.

It would be nice to keep these to allow someone to parse these correctly.

**Comment by rikuson** [comment]
@rahearn
How can I make an absolute date-time value through ical_params?
For example, this code gives me unnecessary strings.

```
event.alarm do |a|
  a.action = 'DISPLAY'
  a.trigger = ''
  a.trigger.ical_params = { 'VALUE' => 'DATE-TIME:19980101T050000Z' }
end
```

Result:

```
TRIGGER;VALUE="DATE-TIME:19980101T050000Z":P
```

**Comment by rahearn** [comment]
Hi @rikuson, this should do it for you:

```ruby
event.alarm do |a|
  a.action = 'DISPLAY'
  a.trigger = Icalendar::Values::DateTime.new("19980101T050000Z")
end
```

**Comment by rikuson** [comment]
It worked!  
Thank you.
