### ISSUE TITLE
icalendar issue for Timezone Australia/Brisbane

### ISSUE THREAD

**Issue by kswathi** [icalendar/icalendar#90]
Hi,

 Am getting error when i try to download the ical for the timezone "Australia/Brisbane". 

when i call   tz.ical_timezone for "Australia/Brisbane"
It is throwing error like this.

NoMethodError (undefined method `offset_from' for nil:NilClass):
  icalendar (1.1.6) lib/icalendar/tzinfo.rb:95:in `daylight'
  icalendar (1.1.6) lib/icalendar/tzinfo.rb:50:in `ical_timezone'

Can you please help me from this.

**Comment by rahearn** [comment]
Closing due to lack of reply.
