### ISSUE TITLE
GMail doesn't recognize ical file

### ISSUE THREAD

**Issue by pruzicka** [icalendar/icalendar#96]
Hi, 
do you know which properties/values needs to present in ical file so that Gmail would recognize file and offer import to Google Calendar (when the file is like attachment in email) ? 
In Gmail there is visible small icon in the email list, so yes, ical is here, but opening the email would show nothing. When I expert event from Facebook (and email it), it would offer import to GCalendar right away.
I've tried different thing but I've found nothing.
Here is my file
##### 

BEGIN:VCALENDAR
VERSION:2.0
PRODID:icalendar-ruby
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
CREATED:20140820T085046Z
ORGANIZER:tester@gmail.com
DTSTAMP:20141017T233215Z
UID:ec1bb65b-75cc-4ec3-95c5-fcd7c0894f6e
DTSTART:20150124T100000
DTEND:20150124T120000
LOCATION:Centrum vitality\, Vídeňská 20\, 779 00 Olomouc
SUMMARY:Stojka I
DESCRIPTION:STOJKA 
CONTACT:tester@gmail.com
END:VEVENT
END:VCALENDAR
##### 

Thanks

Petr R.

**Comment by steeeve** [comment]
@pruzicka did you figure this out?

**Comment by pruzicka** [comment]
Nope :(. It's a strange animal, sometimes Gmail recognize it sometimes it doesn't. Ical file works in iCal however so I don't know what is missing.

**Comment by shyamalaLokre** [comment]
Gmail does not offer 'Add to Calendar' if sender and contact emails are same. Try using different email ids.
